import { defineStore } from 'pinia'

export const useEmployeeStore = defineStore('employee', {
  state: () => ({
    employees: [
      {
        no: 1,
        code: 'M-0001',
        name: '田中 美咲',
        branch: 'マジオネットHD㈱',
        dept: '経営企画部',
        contract: '正社員',
        status: '全て',
      },
      {
        no: 2,
        code: 'M-0002',
        name: '田中 美咲',
        branch: 'マジオネットHD㈱',
        dept: 'データ分析',
        contract: '契約社員',
        status: '処理中',
      },
      {
        no: 3,
        code: 'M-0003',
        name: '加藤 直樹',
        branch: '㈱マジオSD東日本',
        dept: 'デジタル推進課',
        contract: '契約社員',
        status: '訂正中',
      },
      {
        no: 4,
        code: 'M-0004',
        name: '加藤 直樹',
        branch: '㈱マジオSD東日本',
        dept: '教育課',
        contract: '契約社員',
        status: '承認待',
      },
      {
        no: 5,
        code: 'M-0005',
        name: '高橋 健一',
        branch: '㈱マジオSD東日本',
        dept: 'あおぞら課 サポート係',
        contract: '契約社員',
        status: '承認済',
      },
      {
        no: 6,
        code: 'M-0006',
        name: '山本 優子',
        branch: '㈱マジオSD東日本',
        dept: '広報課',
        contract: '契約社員',
        status: '全て',
      },
      {
        no: 7,
        code: 'M-0007',
        name: '小林 恵美',
        branch: '㈱マジオSD東海',
        dept: '講習課',
        contract: '契約社員',
        status: '処理中',
      },
      {
        no: 8,
        code: 'M-0008',
        name: '鈴木 花子',
        branch: '㈱マジオSD東海',
        dept: '講習課',
        contract: '契約社員',
        status: '訂正中',
      },
      {
        no: 9,
        code: 'M-0009',
        name: '吉田 真理',
        branch: '㈱マジオSD東海',
        dept: '広報課',
        contract: '契約社員',
        status: '承認待',
      },
      {
        no: 10,
        code: 'M-0010',
        name: '渡辺 陽太',
        branch: '㈱マジオトラスト',
        dept: '営業戦略部 中国・四国推進課',
        contract: '契約社員',
        status: '承認済',
      },
      {
        no: 11,
        code: 'M-0011',
        name: '井上 智子',
        branch: '㈱マジオトラスト',
        dept: '近畿推進課',
        contract: '契約社員',
        status: '全て',
      },
      {
        no: 12,
        code: 'M-0012',
        name: '佐藤 太郎',
        branch: '㈱マジオトラスト',
        dept: '営業戦略部 サポートセンター課',
        contract: '契約社員',
        status: '処理中',
      },
      {
        no: 13,
        code: 'M-0013',
        name: '佐藤 太郎',
        branch: '㈱マジオトラスト',
        dept: '営業戦略部 サポートセンター課',
        contract: '契約社員',
        status: '訂正中',
      },
      {
        no: 14,
        code: 'M-0014',
        name: '佐藤 太郎',
        branch: '㈱マジオトラスト',
        dept: '営業戦略部 サポートセンター課',
        contract: '契約社員',
        status: '承認待',
      },
      {
        no: 15,
        code: 'M-0015',
        name: '佐藤 太郎',
        branch: '㈱マジオトラスト',
        dept: '営業戦略部 サポートセンター課',
        contract: '契約社員',
        status: '承認済',
      },
      {
        no: 16,
        code: 'M-0016',
        name: '佐藤 太郎',
        branch: '㈱マジオトラスト',
        dept: '営業戦略部 サポートセンター課',
        contract: '契約社員',
        status: '全て',
      },
      {
        no: 17,
        code: 'M-0017',
        name: '佐藤 太郎',
        branch: '㈱マジオトラスト',
        dept: '営業戦略部 サポートセンター課',
        contract: '契約社員',
        status: '処理中',
      },
      {
        no: 18,
        code: 'M-0018',
        name: '佐藤 太郎',
        branch: '㈱マジオトラスト',
        dept: '営業戦略部 サポートセンター課',
        contract: '契約社員',
        status: '訂正中',
      },
      {
        no: 19,
        code: 'M-0019',
        name: '佐藤 太郎',
        branch: '㈱マジオトラスト',
        dept: '営業戦略部 サポートセンター課',
        contract: '契約社員',
        status: '承認待',
      },
      {
        no: 20,
        code: 'M-0020',
        name: '佐藤 太郎',
        branch: '㈱マジオトラスト',
        dept: '営業戦略部 サポートセンター課',
        contract: '契約社員',
        status: '承認済',
      },
    ],
  }),

  getters: {
    getEmployeeById: state => (id: number) => {
      return state.employees.find(emp => emp.no === id)
    },
  },

  actions: {
    async fetchEmployees() {
      // API call implementation
    },
  },
})
